import Head from 'next/head'
import Login from "@/pages/Login";

export default function Home()
{

    return(
        <>
            <Head>
                <title>Handi Connect</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link rel="apple-touch-icon" sizes="180x180" href="/Assets/Favicon/apple-touch-icon.png"/>
                <link rel="icon" type="image/png" sizes="32x32" href="/Assets/Favicon/favicon-32x32.png"/>
                <link rel="icon" type="image/png" sizes="16x16" href="/Assets/Favicon/favicon-16x16.png"/>
                <link rel="manifest" href="/Assets/Favicon/site.webmanifest"/>



            </Head>

            <main>

                <Login/>

            </main>
    </>
  )
}
